// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2024-10-23, 11:27:50 p.m.
const configMerger = require("D:/Coding Projects/ai-chatbot-assistant/ai-chatbot-assistant/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [

].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: { files: ["D:/Coding Projects/ai-chatbot-assistant/ai-chatbot-assistant/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Coding Projects/ai-chatbot-assistant/ai-chatbot-assistant/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Coding Projects/ai-chatbot-assistant/ai-chatbot-assistant/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Coding Projects/ai-chatbot-assistant/ai-chatbot-assistant/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Coding Projects/ai-chatbot-assistant/ai-chatbot-assistant/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Coding Projects/ai-chatbot-assistant/ai-chatbot-assistant/plugins/**/*.{js,ts,mjs}","D:/Coding Projects/ai-chatbot-assistant/ai-chatbot-assistant/composables/**/*.{js,ts,mjs}","D:/Coding Projects/ai-chatbot-assistant/ai-chatbot-assistant/utils/**/*.{js,ts,mjs}","D:/Coding Projects/ai-chatbot-assistant/ai-chatbot-assistant/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/Coding Projects/ai-chatbot-assistant/ai-chatbot-assistant/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/Coding Projects/ai-chatbot-assistant/ai-chatbot-assistant/app.config.{js,ts,mjs}"] } }));

module.exports = config
